language: php
services:
  - mysql
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_install:
  - mv .env.travis .env
  - mysql -e "create database IF NOT EXISTS owg_test;" -uroot
  - composer install
  - php artisan migrate
  - php artisan db:seed

addons:
    code_climate:
        repo_token: 8d02bd491ab893eb31e53cc714124bfd4c6503261e5cd52ca4d48d08741b46e3