language: php
services:
  - mysql
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_install:
  - pip install codecov
  - mv .env.travis .env
  - mysql -e "create database IF NOT EXISTS owg_test;" -uroot
  - composer install
  - php artisan migrate
  - php artisan db:seed

after_success:
  - codecov